<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Nitrapi' => array($vendorDir . '/tituskirch/nitrapi-php-lib/lib'),
);
